name: Docker Image CI

on:
  push:
    branches: [master]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/lnsp/k8s-crash-informer/informer:$(date +%s)
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
